MonPCapplication/Controllers/CatalogController.cs
using MonPCapplication.Models.Mes_Produits;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MonPCapplication.Controllers
{
    public class CatalogController : Controller
    {
        // GET: Catalog
        public ActionResult Index()
        {
            MonPCEntities model = new MonPCEntities();
            CategorieViewModel cVM = new CategorieViewModel(new SelectList(model.CATEGORIEs.ToList(), "id", "nomCategorie"));
            //cVM.ListCatalog = new SelectList(model.CATEGORIEs.ToList(), "id", "nomCategorie");
            return View(cVM);
        }

        public ActionResult getPartialProducts(int? CategId)
        {

            MonPCEntities model = new MonPCEntities();
            PartialProductViewModel vm;
            vm = new PartialProductViewModel();
            List<PRODUIT> list = model.PRODUITs.Where(o => o.appartient_a == CategId).ToList();

            vm.ListProduct = list;

            return PartialView(vm);
        }
    }
}

MonPCapplication/Controllers/PanierController.cs
using MonPCapplication.Models;
using MonPCapplication.Models.Mes_Produits;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MonPCapplication.Controllers
{
    public class PanierController : Controller
    {
        MonPCEntities model = new MonPCEntities();
        // GET: Panier
        public ActionResult Index()
        {
            return View("monPanier");
        }

        // Pour vérifier si un produit existe dans le panier
        private int existeDeja(int id)
        {
            List<Achat> panier = (List<Achat>)Session["panier"];
            for (int i = 0; i < panier.Count; i++)
            {
                if (panier[i].Product.id == id)
                    return i;
            }
            return 0;
        }

        // Pour supprime un produit après vérifier s'il existe dans le panier
        public ActionResult supprimer(int id)
        {
            List<Achat> panier = (List<Achat>)Session["panier"];
            Achat indx = (Achat)panier.FirstOrDefault(o => o.Product.id == id);
            panier.Remove(indx);
            Session["panier"] = panier;
            return View("monPanier");
        }
        public ActionResult FaireLaCommande(int id)
        {
            PRODUIT pr = model.PRODUITs.Find(id);
            if (Session["panier"] == null)
            {
                List<Achat> panier = new List<Achat>();
                panier.Add(new Achat(pr, 1));
                Session["panier"] = panier;
            }
            else
            {
                List<Achat> panier = (List<Achat>)Session["panier"];
                Achat indx = (Achat)panier.FirstOrDefault(o => o.Product.id == id);
                //int indx = existeDeja(id);
                if (indx == null)
                    panier.Add(new Achat(pr, 1));
                else
                    panier.FirstOrDefault(o => o.Product.id == id).Quantite++;
                Session["panier"] = panier;
            }
            return View("monPanier");
        }
        public ActionResult acheter()
        {
            MonPCEntities model = new MonPCEntities();
            List<Achat> panier = (List<Achat>)Session["panier"];
            for (int i = 0; i < panier.Count; i++)
            {
                CLIENT_PRODUIT ach = new CLIENT_PRODUIT();
                ach.idCLIENT = AccountLogin.id_connecté;
                ach.idPRODUIT = panier[i].Product.id;
                ach.quantité = panier[i].Quantite;

                model.CLIENT_PRODUIT.Add(ach);
            }
            model.SaveChanges();

            return View();
        }
    }
}

MonPCapplication/Controllers/ProduitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MonPCapplication.Controllers
{
    public class ProduitController : Controller
    {
        // GET: Produit
        public ActionResult Index(int? id)
        {
            if (id != null)
            {
                MonPCEntities model = new MonPCEntities();
                PRODUIT myProduct = model.PRODUITs.FirstOrDefault(o => o.id == id);
                if (myProduct != null)
                    return View("ProductDetail" , myProduct);
                else
                    return View("error");
            }
            else
            {
                return View("error");
            }
        }
    }
}

MonPCapplication/Views/Produit/ProductDetail.cshtml
@model MonPCapplication.PRODUIT

<div class="col-12 m-3">
    <div class="row bg-light p-3">
        <div class="col-6">
            <img src="~/Images/@Model.image" alt="Denim Jeans" style=" height: 250px; object-fit: contain; ">
        </div>
        <div class="col-6">
            <h3><b>@Model.nomProduit</b></h3>
            <p style=" font-size: 18px;">@Model.Description</p>
            <p style=" color: darkblue; font-size: 18px;"><b>@Model.prix </b>Dh</p>
            <p><button onclick="location.href = '@Url.Action("FaireLaCommande","Panier")?id=@Model.id'" class="btn-primary .bg-secondary.bg-gradient p-2 bg-info rounded-3 w-25"> Add to Cart</button></p>
            <a href="@Url.Action("Index","Produit")?id=@Model.id" class="col-2">Plus de détails</a>
        </div>
    </div>
</div>
<div class="form-group mt-3" align="center">
    <div class="col-md-offset-2 col-md-12 w-100 m-2">
        <input type="submit" value="Voir le catalogue" class="btn btn-default bg-success bg-gradient  text-white fw-bold ps-5 pe-5" onclick=" location.href = '@Url.Action("Index","Catalog")'" />
    </div>
    <div class="col-md-offset-2 col-md-12 w-100 m-2">
        <input type="submit" value="Revenir à page d'accueil" class="btn btn-default bg-success bg-gradient  text-white fw-bold ps-5 pe-5" onclick=" location.href = '@Url.Action("Index","Home")'" />
    </div>
</div>