MonPCapplication/Controllers/AdminController.cs
using MonPCapplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MonPCapplication.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetProducts()
        {
            MonPCEntities model = new MonPCEntities();
            var products = model.PRODUITs.Select(o => new {
                nomProduit = o.nomProduit,
                prix = o.prix,
                quantité = o.quantité,
                appartient_a = model.CATEGORIEs.FirstOrDefault(s => s.id == o.appartient_a).nomCategorie,
                ajoute_par = model.FOURNISSEURs.FirstOrDefault(s => s.id == o.ajoute_par).username,
                id = o.id
            }).ToList();
            return Json(new { data = products }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AjoutProd()
        {
            PRODUIT pr = new PRODUIT();
            return View(pr);
        }
        [HttpPost]
        public ActionResult AjoutProd(string nomProduit, string Description, HttpPostedFileBase image, float prix, int quantité, int nomCategorie)
        {
            MonPCEntities model = new MonPCEntities();
            PRODUIT pr = new PRODUIT();
            string pic = null;
            if (image != null)
            {
                pic = System.IO.Path.GetFileName(image.FileName);
                string path = System.IO.Path.Combine(Server.MapPath("~/Images"), pic);
                image.SaveAs(path);
            }
            pr.nomProduit = nomProduit;
            pr.Description = Description;
            pr.image = pic;
            pr.prix =(decimal) prix;
            pr.quantité = quantité;
            pr.appartient_a = model.CATEGORIEs.FirstOrDefault(o => o.id == nomCategorie).id;
            pr.ajoute_par = model.FOURNISSEURs.FirstOrDefault(o => o.id == AccountLogin.id_connecté).id;


            model.PRODUITs.Add(pr);
            model.SaveChanges();
            return RedirectToAction("Index","Home");
        }

        public ActionResult supprimerProd(int id)
        {
            MonPCEntities model = new MonPCEntities();
            PRODUIT pr = new PRODUIT();
            pr = model.PRODUITs.FirstOrDefault(o => o.id == id);
            model.PRODUITs.Remove(pr);
            model.SaveChanges();
            return RedirectToAction("Index", "Home");
        }

    }
}

MonPCapplication/Controllers/CatalogController.cs
using MonPCapplication.Models.Mes_Produits;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MonPCapplication.Controllers
{
    public class CatalogController : Controller
    {
        // GET: Catalog
        public ActionResult Index()
        {
            MonPCEntities model = new MonPCEntities();
            CategorieViewModel cVM = new CategorieViewModel(new SelectList(model.CATEGORIEs.ToList(), "id", "nomCategorie"));
            //cVM.ListCatalog = new SelectList(model.CATEGORIEs.ToList(), "id", "nomCategorie");
            return View(cVM);
        }

        public ActionResult getPartialProducts(int? CategId)
        {

            MonPCEntities model = new MonPCEntities();
            PartialProductViewModel vm;
            vm = new PartialProductViewModel();
            List<PRODUIT> list = model.PRODUITs.Where(o => o.appartient_a == CategId).ToList();

            vm.ListProduct = list;

            return PartialView(vm);
        }
    }
}

MonPCapplication/Controllers/PanierController.cs
using MonPCapplication.Models;
using MonPCapplication.Models.Mes_Produits;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MonPCapplication.Controllers
{
    public class PanierController : Controller
    {
        MonPCEntities model = new MonPCEntities();
        // GET: Panier
        public ActionResult Index()
        {
            return View("monPanier");
        }

        // Pour vérifier si un produit existe dans le panier
        private int existeDeja(int id)
        {
            List<Achat> panier = (List<Achat>)Session["panier"];
            for (int i = 0; i < panier.Count; i++)
            {
                if (panier[i].Product.id == id)
                    return i;
            }
            return 0;
        }

        // Pour supprime un produit après vérifier s'il existe dans le panier
        public ActionResult supprimer(int id)
        {
            List<Achat> panier = (List<Achat>)Session["panier"];
            Achat indx = (Achat)panier.FirstOrDefault(o => o.Product.id == id);
            panier.Remove(indx);
            Session["panier"] = panier;
            return View("monPanier");
        }
        public ActionResult FaireLaCommande(int id)
        {
            PRODUIT pr = model.PRODUITs.Find(id);
            if (Session["panier"] == null)
            {
                List<Achat> panier = new List<Achat>();
                panier.Add(new Achat(pr, 1));
                Session["panier"] = panier;
            }
            else
            {
                List<Achat> panier = (List<Achat>)Session["panier"];
                Achat indx = (Achat)panier.FirstOrDefault(o => o.Product.id == id);
                //int indx = existeDeja(id);
                if (indx == null)
                    panier.Add(new Achat(pr, 1));
                else
                    panier.FirstOrDefault(o => o.Product.id == id).Quantite++;
                Session["panier"] = panier;
            }
            return View("monPanier");
        }
        public ActionResult acheter()
        {
            MonPCEntities model = new MonPCEntities();
            List<Achat> panier = (List<Achat>)Session["panier"];
            for (int i = 0; i < panier.Count; i++)
            {
                CLIENT_PRODUIT ach = new CLIENT_PRODUIT();
                ach.idCLIENT = AccountLogin.id_connecté;
                ach.idPRODUIT = panier[i].Product.id;
                ach.quantité = panier[i].Quantite;

                model.CLIENT_PRODUIT.Add(ach);
            }
            model.SaveChanges();

            return View();
        }
    }
}

MonPCapplication/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MonPCapplication.Models.Mes_Produits;

namespace MonPCapplication.Controllers
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult Index()

        {
            PartialProductViewModel vm = new PartialProductViewModel();
            vm.ListProduct = new List<PRODUIT>();
            return View(vm);
        }
        [HttpGet]
        public ActionResult Index(string myProd)
        {
            MonPCEntities model = new MonPCEntities();
            PartialProductViewModel vm = new PartialProductViewModel();
            vm.ListProduct = new List<PRODUIT>();
            vm.ListProduct = model.PRODUITs.Where(o => o.nomProduit.Contains(myProd) || o.Description.Contains(myProd)).ToList();

            return View(vm);
        }
    }
}

MonPCapplication/Views/Shared/_Layout.cshtml
@using MonPCapplication.Models
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Styles/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <link href="~/Styles/css/style1.css" rel="stylesheet" type="text/css" />
    <link href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />

</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-text mt-3 rounded-2 border border-secondary" style="background-color: #e3f2fd;">
            <div class="container-fluid">
                <a class="navbar-brand ms-2" href='@Url.Action("Index","Home")'><b>MonPC </b>store</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarScroll">
                    <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                        <li class="nav-item">
                            <a class="nav-link  ms-5" aria-current="page" href='@Url.Action("Index","Home")'>Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link ms-3" aria-current="page" href='@Url.Action("Index","Catalog")'>Catalogue</a>
                        </li>
                        @if (AccountLogin.est_admin == 1)
                        {
                            <li class="nav-item">
                            <a class="nav-link ms-3" aria-current="page" href='@Url.Action("Index","Admin")'>Gestion des produits</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link ms-3" aria-current="page" href='@Url.Action("AjoutProd","Admin")'>Ajouter produit</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link ms-3" aria-current="page" href='@Url.Action("About","Home")'>à propos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link  ms-3" aria-current="page" href='@Url.Action("ContactUs","Home")'>Contact</a>
                        </li>
                    </ul>
                    <form class="d-flex" action='@Url.Action("Index","Search")' method="post">
                        <button class="btn btn-outline-success" type="submit">Rechercher produits</button>
                    </form>
                    @if (AccountLogin.est_connecté == 0)
                    {

                        <a class="p-2 pt-1 mt-1 nav-link ms-3 fw-bolder" href='@Url.Action("Login","Account")'> Login <img src="~/Images/avatar.png" style=" height: 25px; object-fit: contain;" /></a>
                    }
                    else
                    {
                        <a class="p-2 pt-1 mt-1 nav-link ms-3 fw-bolder" href='@Url.Action("Login","Account")' onclick="@AccountLogin.est_connecté=0; @AccountLogin.est_admin =0;"> Logout <img src="~/Images/avatar.png" style=" height: 25px; object-fit: contain; " /></a>
                        <button type="button" class=" bg-transparent p-2" style="border-radius: 50%; border: none; " onclick="location.href= '@Url.Action("Index","Panier")'">
                            <b><a class="fa fa-shopping-basket"></a></b>
                        </button>
                    }

                </div>
            </div>
        </nav>
        <div class="container body-content ">
            @RenderBody()
            <hr />

            <footer class="text-center">
                <p>&copy; @DateTime.Now.Year - Crée par : Sohaib Skious</p>
            </footer>
        </div>
    </div>
    <script src="cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
        });
    </script>
</body>
</html>